from django.db import models

# Create your models here.

class Strain(models.Model):
    strain_id = models.AutoField(primary_key=True)

    #Раздел 1 – Наименование штамма, такcономия, номенклатура, степень риска
    CollectionCode = models.CharField(max_length = 255)
    Subcollection = models.CharField(max_length = 255)
    Subcollection1 = models.CharField(max_length = 255)
    Genus = models.CharField(max_length = 255)
    Species = models.CharField(max_length = 255)
    Variant = models.CharField(max_length = 255, blank = True)
    Forma = models.CharField(max_length = 255, blank = True)
    FormaSpecies = models.CharField(max_length = 255, blank = True)
    Strain = models.FloatField()
    AuthoritySp = models.CharField(max_length = 255)
    AuthoritySubSp = models.CharField(max_length = 255, blank = True)
    Family = models.CharField(max_length = 255, blank = True)
    Order = models.CharField(max_length = 255, blank = True)
    Class = models.CharField(max_length = 255, blank = True)
    Synonym = models.TextField(blank = True)
    TaxonomicID = models.CharField(max_length = 255, blank = True)
    Current_Name = models.CharField(max_length = 255, blank = True)
    Link_to_TaxonomicID = models.CharField(max_length = 255, blank = True)
    Pathogenicgroup = models.CharField(max_length = 255, blank = True)
    Risk_group = models.CharField(max_length = 255, blank = True)
    SanPin = models.CharField(max_length = 255, blank = True)
    State = models.CharField(max_length = 255, blank = True)
    TypeRus = models.CharField(max_length = 255, blank = True)
    TypeEng = models.CharField(max_length = 255, blank = True)
    accepted_name = models.CharField(max_length = 255, blank = True)
    OtherName = models.CharField(max_length = 255, blank = True)
    ClassShort = models.CharField(max_length = 255, blank = True)
    References = models.TextField(blank = True)
    References_nc = models.TextField(blank = True)
    Race = models.CharField(max_length = 255, blank = True)
    Serovar = models.CharField(max_length = 255, blank = True)
    OtherCol = models.TextField(blank = True)

    #Раздел 2 – История штамма
    ReceivedFromRus = models.CharField(max_length = 255)
    ReceivedFromEng = models.CharField(max_length = 255)
    DepositorRus = models.CharField(max_length = 255, blank = True)
    DepositorEng = models.CharField(max_length = 255, blank = True)
    ReceivedAs = models.CharField(max_length = 255)
    ReceivedDate = models.DateField(null = True, blank = True)
    AccessionDate = models.CharField(max_length = 255, null = True, blank = True)
    TypeOfSubstrateRus = models.CharField(max_length = 255)
    TypeOfSubstrateEng = models.CharField(max_length = 255)
    IsolatedFromRus = models.CharField(max_length = 255)
    IsolatedFromEng = models.CharField(max_length = 255)
    AnatomicPartRus = models.CharField(max_length = 255, blank = True)
    AnatomicPartEng = models.CharField(max_length = 255, blank = True)
    LocationRus = models.CharField(max_length = 255, blank = True)
    LocationEng = models.CharField(max_length = 255, blank = True)
    GeographicsRus = models.CharField(max_length = 255, blank = True)
    GeographicsEng = models.CharField(max_length = 255, blank = True)
    CountryRus = models.CharField(max_length = 255, blank = True)
    CountryEng = models.CharField(max_length = 255, blank = True)
    USSR = models.CharField(max_length = 255, blank = True)
    CollectedByRus = models.CharField(max_length = 255, blank = True)
    CollectedByEng = models.CharField(max_length = 255, blank = True)
    CollectedDate = models.DateField(null = True, blank = True)
    IsolationDate = models.DateField(null = True, blank = True)
    IsolatedByRus = models.CharField(max_length = 255, blank = True)
    IsolatedByEng = models.CharField(max_length = 255, blank = True)
    IsolateNumberRus = models.CharField(max_length = 255, blank = True)
    IsolateNumberEng = models.CharField(max_length = 255, blank = True)
    IdentificateByRus = models.CharField(max_length = 255, blank = True)
    IdentificateByEng = models.CharField(max_length = 255, blank = True)
    IdentificateDate = models.CharField(max_length = 255, blank = True)

    #Раздел 3 – Культивирование и хранение штамма
    IncubationTemp = models.CharField(max_length = 255)
    Tested_temperature_growth_range = models.CharField(max_length = 255, blank = True)
    GrowthMedium = models.CharField(max_length = 255)
    GrowthConditionRus = models.CharField(max_length=255, blank = True)
    GrowthConditionEng = models.CharField(max_length = 255, blank = True)
    StorageMethods = models.CharField(max_length = 255)
    StorageFreeze = models.CharField(max_length = 255, blank = True)
    StorageOil = models.CharField(max_length = 255, blank = True)
    StorageSilicagel = models.CharField(max_length = 255, blank = True)
    StorageWater = models.CharField(max_length = 255, blank = True)
    StorageNitrogen = models.CharField(max_length = 255, blank = True)
    StorageSubcultivation = models.CharField(max_length = 255, blank = True)
    StorageSoil = models.CharField(max_length = 255, blank = True)

    #Раздел 4 – Характеристика штамма
    EnzymeProductionEng = models.CharField(max_length = 255, blank = True)
    MeraboliteProductionEng = models.CharField(max_length = 255, blank = True)
    TransformationEng = models.CharField(max_length = 255, blank = True)
    DegradationEng = models.CharField(max_length = 255, blank = True)
    OtherRus = models.TextField(blank = True)
    OtherEng = models.TextField(blank = True)
    MatingType = models.CharField(max_length = 255, blank = True)
    DNA_Sequence_Accession_Numbers = models.CharField(max_length = 255, blank = True)

    #Раздел 5 – Общая информация
    Latitude = models.CharField(max_length = 255, blank = True)
    Longitude = models.CharField(max_length = 255, blank = True)
    Altitude = models.CharField(max_length = 255, blank = True)
    Curator = models.CharField(max_length = 255)
    Category = models.CharField(max_length = 255, blank = True)
    Restrictions_on_use = models.CharField(max_length = 255, blank = True)
    Remarks = models.CharField(max_length = 255)
    EntryDate = models.DateField(null = True, blank = True)
    EditDate = models.DateField(null = True, blank = True)
    ReidentifRus = models.CharField(max_length = 255, blank = True)
    ReidentifEng = models.CharField(max_length = 255, blank = True)
    Confidential_Information = models.CharField(max_length = 255, blank = True)
    ApplicationRus = models.CharField(max_length = 255, blank = True)
    ApplicationEng = models.CharField(max_length = 255, blank = True)
    Form_of_supply = models.CharField(max_length = 255, blank = True)
    Report2020 = models.CharField(max_length = 255, blank = True)
    Report2021 = models.CharField(max_length = 255, blank = True)
    EnzymeProductionRus = models.CharField(max_length = 255, blank = True)
    MeraboliteProductionRus = models.CharField(max_length = 255, blank = True)
    TransformationRus = models.CharField(max_length = 255, blank = True)
    DegradationRus = models.CharField(max_length = 255, blank = True)
    class Meta:
        verbose_name_plural = 'strains'
