# Generated by Django 5.1.5 on 2025-02-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strains',
            options={'verbose_name_plural': 'strains'},
        ),
    ]
